### ISSUE TITLE
QR Decomposition Broken for Larger filebacked.big.matrix

### ISSUE THREAD

**Issue by jonpeake** [cdeterman/bigalgebra#4]
I'm having trouble with qr for big.matrix applications. It seems to work for a small matrix (i.e., 1000x4) but not for larger matrices (i.e., 10000x4). Any idea what could be causing this? Whenever I try a larger matrix, it crashes R (fatal error). When run inside a command prompt, I get: 
```
 *** caught bus error ***
address 0x7fea30dbe000, cause 'non-existent physical address'

Traceback:
 1: CreateFileBackedBigMatrix(as.character(backingfile), as.character(backingpath),     as.double(nrow), as.double(ncol), as.character(colnames),     as.character(rownames), as.integer(typeVal), as.double(init),     as.logical(separated))
 2: filebacked.big.matrix(m, n, type, init = val, backingfile = f,     backingpath = p, descriptorfile = d)
 3: anon_matrix(M, M, val = 0)
 4: dgeqrf(x)
 5: qr(A)
 6: qr(A)

```
I'm using R 3.5.1 on an Ubuntu 18.10 machine.

**Comment by cdeterman** [comment]
@jonpeake It has been a while since I have had time to touch this package.  Quite a bit needs to be redone and I am not sure why the larger matrices would be causing a problem.  I will take a look when I can but unfortunately I have quite a few other things (namely my primary job) that are taking up most of my time.  Hopefully I can find some time to have a look at this but I can't make any promises.

**Comment by jonpeake** [comment]
@cdeterman I actually ended up reinstalling my linux build because I was running across some other bugs, and after clean installing Ubuntu 18.04 I haven't had the qr problem again. My guess is that it was something to do with the disk not being used/accessed properly. Thanks for the reply though!

**Comment by cdeterman** [comment]
Glad to hear, for now I will close this issue then.  Please feel free to update if you run in to any additional problems.
